// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAq8MJRFdfomLGPHh0_cKaz-nrjv8s0wY',
    appId: '1:789136571111:web:5a77dedf88dec93b5d0042',
    messagingSenderId: '789136571111',
    projectId: 'flutter-ecommerce-73435',
    authDomain: 'flutter-ecommerce-73435.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-73435.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkBauX8UCphBmKiFQFdbFjvO8T6luYHpM',
    appId: '1:789136571111:android:3d5dbd249cfd5dad5d0042',
    messagingSenderId: '789136571111',
    projectId: 'flutter-ecommerce-73435',
    storageBucket: 'flutter-ecommerce-73435.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwKEgwfY1fnYAxCzdI8dKFzzYGakpM_Zg',
    appId: '1:789136571111:ios:4f6e4f392a414c745d0042',
    messagingSenderId: '789136571111',
    projectId: 'flutter-ecommerce-73435',
    storageBucket: 'flutter-ecommerce-73435.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwKEgwfY1fnYAxCzdI8dKFzzYGakpM_Zg',
    appId: '1:789136571111:ios:4f6e4f392a414c745d0042',
    messagingSenderId: '789136571111',
    projectId: 'flutter-ecommerce-73435',
    storageBucket: 'flutter-ecommerce-73435.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAq8MJRFdfomLGPHh0_cKaz-nrjv8s0wY',
    appId: '1:789136571111:web:e40b6afa2b9932885d0042',
    messagingSenderId: '789136571111',
    projectId: 'flutter-ecommerce-73435',
    authDomain: 'flutter-ecommerce-73435.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-73435.appspot.com',
  );

}